services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U  -d  || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./sessions:/app/sessions
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8501:8501"
    environment:
      DASHBOARD_USERNAME: 
      DASHBOARD_PASSWORD: 
    volumes:
      - ./sessions:/app/sessions
      - ./dashboard:/app/dashboard
    restart: unless-stopped

volumes:
  pgdata:
